export const ADD_FETCHED_DATA = 'ADD_FETCHED_DATA';
export const SHOW_LOADING_BAR = 'SHOW_LOADING_BAR';
export const HIDE_LOADING_BAR = 'HIDE_LOADING_BAR';
export const ADD_FETCHED_DATA_ALBUM = 'ADD_FETCHED_DATA_ALBUM';
export const ADD_FETCHED_DATA_ALBUM_PHOTO = 'ADD_FETCHED_DATA_ALBUM_PHOTO';
export const ADD_FETCHED_DATA_POST = 'ADD_FETCHED_DATA_POST';
export const ADD_FETCHED_DATA_POST_COMMENTS = 'ADD_FETCHED_DATA_POST_COMMENTS';